"""create_notepad_model

Revision ID: 692cf05ef43d
Revises: 6a13c584066e
Create Date: 2026-09-20 17:16:33.690268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692cf05ef43d'
down_revision = '6a13c584066e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notepad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notepad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
